services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${TOKEN}
      - UPDATE_IP=ipv4
      - LOG_FILE=false
    volumes:
      - ./data/duckdns/appdata/config:/config
    restart: unless-stopped
